/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as authAuthSignUpRouteImport } from './routes/(auth)/_auth/sign-up'
import { Route as authAuthSignInRouteImport } from './routes/(auth)/_auth/sign-in'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/_auth/reset-password'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/_auth/forgot-password'
import { Route as authApiAuthSplatRouteImport } from './routes/(auth)/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignUpRoute = authAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthSignInRoute = authAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authApiAuthSplatRoute = authApiAuthSplatRouteImport.update({
  id: '/(auth)/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/sign-in': typeof authAuthSignInRoute
  '/sign-up': typeof authAuthSignUpRoute
  '/api/auth/$': typeof authApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/sign-in': typeof authAuthSignInRoute
  '/sign-up': typeof authAuthSignUpRoute
  '/api/auth/$': typeof authApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(auth)/_auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/_auth/reset-password': typeof authAuthResetPasswordRoute
  '/(auth)/_auth/sign-in': typeof authAuthSignInRoute
  '/(auth)/_auth/sign-up': typeof authAuthSignUpRoute
  '/(auth)/api/auth/$': typeof authApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/_auth'
    | '/(auth)/verify-email'
    | '/(auth)/_auth/forgot-password'
    | '/(auth)/_auth/reset-password'
    | '/(auth)/_auth/sign-in'
    | '/(auth)/_auth/sign-up'
    | '/(auth)/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  authApiAuthSplatRoute: typeof authApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/sign-up': {
      id: '/(auth)/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authAuthSignUpRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/sign-in': {
      id: '/(auth)/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthSignInRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/reset-password': {
      id: '/(auth)/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-password': {
      id: '/(auth)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/api/auth/$': {
      id: '/(auth)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof authApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authAuthRouteChildren {
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
  authAuthSignInRoute: typeof authAuthSignInRoute
  authAuthSignUpRoute: typeof authAuthSignUpRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
  authAuthSignInRoute: authAuthSignInRoute,
  authAuthSignUpRoute: authAuthSignUpRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  authAuthRoute: authAuthRouteWithChildren,
  authVerifyEmailRoute: authVerifyEmailRoute,
  authApiAuthSplatRoute: authApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
